import { Link } from "react-router-dom";
import { Heart, Shield, MessageCircle, ArrowRight, CheckCircle, Sparkles, Camera, FileText, Mic } from "lucide-react";
import { motion } from "framer-motion";
import { ImageWithFallback } from "../components/figma/ImageWithFallback.jsx";

const fadeUp = {
  hidden: { opacity: 0, y: 30 },
  visible: (i = 0) => ({
    opacity: 1,
    y: 0,
    transition: { duration: 0.6, delay: i * 0.15, ease: [0.25, 0.46, 0.45, 0.94] },
  }),
};

const stagger = {
  visible: { transition: { staggerChildren: 0.12 } },
};

export default function Landing() {
  const features = [
    {
      icon: MessageCircle,
      title: "AI Health Assistant",
      desc: "24/7 voice-enabled AI support answers your recovery questions instantly with personalized guidance.",
    },
    {
      icon: Camera,
      title: "Smart Wound Analysis",
      desc: "Take a photo of your incision and get instant AI-powered feedback on healing progress.",
    },
    {
      icon: FileText,
      title: "Record Digitization",
      desc: "Upload discharge summaries and get structured, actionable recovery plans generated by AI.",
    },
    {
      icon: Mic,
      title: "Multilingual Voice",
      desc: "Describe symptoms in Hindi, English, or Hinglish — our AI transcribes and understands all.",
    },
  ];

  const steps = [
    { title: "Upload Discharge Summary", desc: "Upload your post-surgery PDF and let AI extract the key data" },
    { title: "Get Your Recovery Plan", desc: "AI generates a personalized daily schedule with medications and tasks" },
    { title: "Track & Monitor Daily", desc: "Check off tasks, analyze wounds, and chat with your AI assistant" },
    { title: "Stay Safe at Home", desc: "Get alerts for concerns and seamless pharmacy medication management" },
  ];

  return (
    <div className="min-h-screen bg-[#D3D0BC] overflow-x-hidden">
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-[#3E435D]/95 backdrop-blur-md border-b border-white/5">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2.5 group">
            <div className="w-9 h-9 bg-[#CBC3A5] rounded-xl flex items-center justify-center group-hover:scale-105 transition-transform">
              <Heart className="w-5 h-5 text-[#3E435D]" />
            </div>
            <span className="text-[#D3D0BC] text-xl font-bold tracking-tight">SurgiSense</span>
          </Link>
          <Link
            to="/dashboard"
            className="bg-[#CBC3A5] text-[#3E435D] px-5 py-2.5 rounded-xl font-semibold text-sm hover:bg-[#D3D0BC] transition-all hover:shadow-lg hover:shadow-[#CBC3A5]/20"
          >
            Get Started
          </Link>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="pt-28 pb-20 px-6 relative">
        <div className="absolute top-20 left-10 w-72 h-72 bg-[#CBC3A5]/30 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute bottom-10 right-10 w-96 h-96 bg-[#9AA7B1]/20 rounded-full blur-3xl pointer-events-none" />

        <div className="max-w-7xl mx-auto relative">
          <div className="grid lg:grid-cols-2 gap-16 items-center">
            <motion.div initial="hidden" animate="visible" variants={stagger}>
              <motion.div variants={fadeUp} custom={0} className="inline-flex items-center gap-2 bg-[#3E435D]/10 backdrop-blur-sm border border-[#3E435D]/10 px-4 py-2 rounded-full mb-6">
                <Sparkles className="w-4 h-4 text-[#3E435D]" />
                <span className="text-[#3E435D] text-sm font-medium">AI-Powered Post-Surgical Recovery</span>
              </motion.div>

              <motion.h1 variants={fadeUp} custom={1} className="text-[#3E435D] text-4xl sm:text-5xl lg:text-6xl font-bold leading-[1.1] tracking-tight mb-6">
                Your Intelligent
                <span className="block bg-gradient-to-r from-[#3E435D] to-[#9AA7B1] bg-clip-text text-transparent">
                  Recovery Companion
                </span>
              </motion.h1>

              <motion.p variants={fadeUp} custom={2} className="text-[#3E435D]/70 text-lg lg:text-xl max-w-lg mb-8 leading-relaxed">
                Personalized guidance, 24/7 AI support, wound monitoring, and smart medication management — all in one place.
              </motion.p>

              <motion.div variants={fadeUp} custom={3} className="flex flex-col sm:flex-row gap-3">
                <Link
                  to="/dashboard"
                  className="group bg-[#3E435D] text-[#D3D0BC] px-7 py-3.5 rounded-xl font-semibold text-base hover:bg-[#4a5070] transition-all flex items-center justify-center gap-2 shadow-lg shadow-[#3E435D]/25 hover:shadow-xl hover:shadow-[#3E435D]/30"
                >
                  Start Recovery
                  <ArrowRight className="w-4 h-4 group-hover:translate-x-0.5 transition-transform" />
                </Link>
                <Link
                  to="/record-digitization"
                  className="border-2 border-[#3E435D]/20 text-[#3E435D] px-7 py-3.5 rounded-xl font-semibold text-base hover:bg-[#3E435D] hover:text-[#D3D0BC] hover:border-[#3E435D] transition-all text-center"
                >
                  Upload Records
                </Link>
              </motion.div>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, scale: 0.95, x: 20 }}
              animate={{ opacity: 1, scale: 1, x: 0 }}
              transition={{ duration: 0.8, delay: 0.3, ease: "easeOut" }}
              className="relative hidden lg:block"
            >
              <div className="relative rounded-3xl overflow-hidden shadow-2xl shadow-[#3E435D]/15">
                <ImageWithFallback
                  src="https://plus.unsplash.com/premium_photo-1661767897334-bbfbdfdc4d1a?q=80&w=1170&auto=format&fit=crop"
                  alt="Healthcare professional helping patient"
                  className="w-full h-auto object-cover aspect-[4/3]"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-[#3E435D]/40 via-transparent to-transparent" />
              </div>

              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.8, duration: 0.5 }}
                className="absolute -bottom-6 -left-6 bg-white/90 backdrop-blur-lg rounded-2xl p-4 shadow-xl border border-white/50"
              >
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-[#CBC3A5] rounded-xl flex items-center justify-center">
                    <Shield className="w-5 h-5 text-[#3E435D]" />
                  </div>
                  <div>
                    <p className="text-[#3E435D] font-semibold text-sm">HIPAA Compliant</p>
                    <p className="text-[#9AA7B1] text-xs">Enterprise-grade security</p>
                  </div>
                </div>
              </motion.div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-6 bg-white/60 backdrop-blur-sm">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            variants={stagger}
            className="text-center mb-14"
          >
            <motion.h2 variants={fadeUp} className="text-[#3E435D] text-3xl md:text-4xl font-bold tracking-tight mb-4">
              Everything You Need to Recover
            </motion.h2>
            <motion.p variants={fadeUp} custom={1} className="text-[#9AA7B1] text-lg max-w-2xl mx-auto">
              Powered by advanced AI to give you hospital-grade support at home
            </motion.p>
          </motion.div>

          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-80px" }}
            variants={stagger}
            className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5"
          >
            {features.map((f) => (
              <motion.div
                key={f.title}
                variants={fadeUp}
                className="group bg-white rounded-2xl p-6 shadow-sm border border-[#3E435D]/5 hover:shadow-lg hover:border-[#CBC3A5]/50 transition-all duration-300 hover:-translate-y-1"
              >
                <div className="w-12 h-12 bg-[#3E435D] rounded-xl flex items-center justify-center mb-4 group-hover:scale-105 transition-transform">
                  <f.icon className="w-6 h-6 text-[#CBC3A5]" />
                </div>
                <h3 className="text-[#3E435D] text-lg font-semibold mb-2">{f.title}</h3>
                <p className="text-[#9AA7B1] text-sm leading-relaxed">{f.desc}</p>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-20 px-6">
        <div className="max-w-4xl mx-auto">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            variants={stagger}
            className="text-center mb-14"
          >
            <motion.h2 variants={fadeUp} className="text-[#3E435D] text-3xl md:text-4xl font-bold tracking-tight mb-4">
              Simple Steps to Better Recovery
            </motion.h2>
          </motion.div>

          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-60px" }}
            variants={stagger}
            className="space-y-4"
          >
            {steps.map((item, i) => (
              <motion.div
                key={i}
                variants={fadeUp}
                custom={i}
                className="group flex gap-5 items-start bg-white/80 backdrop-blur-sm rounded-2xl p-5 border border-[#3E435D]/5 hover:bg-white hover:shadow-md transition-all duration-300"
              >
                <div className="w-11 h-11 bg-[#CBC3A5] text-[#3E435D] rounded-full flex items-center justify-center text-lg font-bold shrink-0 group-hover:scale-105 transition-transform">
                  {i + 1}
                </div>
                <div>
                  <h3 className="text-[#3E435D] text-lg font-semibold mb-1">{item.title}</h3>
                  <p className="text-[#9AA7B1] text-sm leading-relaxed">{item.desc}</p>
                </div>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Trust Section */}
      <section className="py-20 px-6 bg-[#3E435D]">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            variants={stagger}
            className="grid lg:grid-cols-2 gap-14 items-center"
          >
            <motion.div variants={fadeUp}>
              <h2 className="text-[#D3D0BC] text-3xl md:text-4xl font-bold tracking-tight mb-8">
                Hospital-Grade Safety<br />You Can Trust
              </h2>
              <ul className="space-y-4">
                {[
                  "HIPAA-compliant secure platform",
                  "AI suggestions backed by medical protocols",
                  "Direct escalation to healthcare providers",
                  "Designed for elderly patients & caregivers",
                ].map((item) => (
                  <motion.li key={item} variants={fadeUp} className="flex items-start gap-3 text-[#D3D0BC]/90">
                    <CheckCircle className="w-5 h-5 text-[#CBC3A5] shrink-0 mt-0.5" />
                    <span className="text-base">{item}</span>
                  </motion.li>
                ))}
              </ul>
            </motion.div>

            <motion.div variants={fadeUp} custom={2} className="hidden lg:block">
              <div className="rounded-2xl overflow-hidden shadow-2xl">
                <ImageWithFallback
                  src="https://images.unsplash.com/photo-1686052401814-d0430982f8f4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080"
                  alt="Medical professional caring for patient"
                  className="w-full h-auto object-cover aspect-[4/3]"
                />
              </div>
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24 px-6 relative">
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-[#CBC3A5]/20 rounded-full blur-3xl" />
        </div>
        <motion.div
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true }}
          variants={stagger}
          className="max-w-3xl mx-auto text-center relative"
        >
          <motion.h2 variants={fadeUp} className="text-[#3E435D] text-3xl md:text-4xl font-bold tracking-tight mb-5">
            Ready to Start Your Recovery?
          </motion.h2>
          <motion.p variants={fadeUp} custom={1} className="text-[#9AA7B1] text-lg mb-8 max-w-xl mx-auto">
            Join patients recovering safely at home with AI-powered guidance from SurgiSense.
          </motion.p>
          <motion.div variants={fadeUp} custom={2}>
            <Link
              to="/dashboard"
              className="group inline-flex items-center gap-2 bg-[#3E435D] text-[#D3D0BC] px-8 py-4 rounded-xl font-semibold text-lg hover:bg-[#4a5070] transition-all shadow-lg shadow-[#3E435D]/25 hover:shadow-xl"
            >
              Start Free Trial
              <ArrowRight className="w-5 h-5 group-hover:translate-x-0.5 transition-transform" />
            </Link>
          </motion.div>
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="bg-[#3E435D] py-8 border-t border-white/5">
        <div className="max-w-7xl mx-auto px-6 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 bg-[#CBC3A5] rounded-lg flex items-center justify-center">
              <Heart className="w-4 h-4 text-[#3E435D]" />
            </div>
            <span className="text-[#D3D0BC] font-semibold">SurgiSense</span>
          </div>
          <p className="text-[#9AA7B1] text-sm">© 2026 SurgiSense. Your trusted recovery companion.</p>
        </div>
      </footer>
    </div>
  );
}
